export const DISCORD_OAUTH_LINK = process.env.NEXT_PUBLIC_DISCORD_OAUTH_LINK;
export const GOOGLE_OAUTH_LINK = process.env.NEXT_PUBLIC_GOOGLE_OAUTH_LINK;
export const GITHUB_OAUTH_LINK = process.env.NEXT_PUBLIC_GITHUB_OAUTH_LINK;
